var Calculator = {
  decimal: false,
  limite: 8, decimal : false,
  limite: 8,
  negativo: false,
  numero: 0,
  cont: 0,
  i: 0,
  sw: false,
  temp: "",
  operacionactual: "",
  ultimaoperacion: "",
  primernumero: 0,
  segundonumero: 0,
  resultadofinal: 0,
  resultadointermedio: 0,
  funciones : ["CE","division", "multiplicacion", "resta","suma","igual"],
  calculos : ["suma", "resta", "multiplicacion","division"],
  numeros : ["1", "2", "3", "4", "5","6","7","8","9","0","sign","punto","."],
  tecla : document.getElementsByClassName("teclado")[0],
  pantalla : document.getElementById("display"),
}
